# Generated by Django 3.2.5 on 2021-07-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captiondoc', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='doc/%y')),
            ],
        ),
    ]
